// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driver.proto

package driverpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type InitClusterRequest struct {
	Force                bool     `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Snapshot             string   `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitClusterRequest) Reset()         { *m = InitClusterRequest{} }
func (m *InitClusterRequest) String() string { return proto.CompactTextString(m) }
func (*InitClusterRequest) ProtoMessage()    {}
func (*InitClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{2}
}

func (m *InitClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitClusterRequest.Unmarshal(m, b)
}
func (m *InitClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitClusterRequest.Marshal(b, m, deterministic)
}
func (m *InitClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitClusterRequest.Merge(m, src)
}
func (m *InitClusterRequest) XXX_Size() int {
	return xxx_messageInfo_InitClusterRequest.Size(m)
}
func (m *InitClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitClusterRequest proto.InternalMessageInfo

func (m *InitClusterRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *InitClusterRequest) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

type InitClusterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitClusterResponse) Reset()         { *m = InitClusterResponse{} }
func (m *InitClusterResponse) String() string { return proto.CompactTextString(m) }
func (*InitClusterResponse) ProtoMessage()    {}
func (*InitClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{3}
}

func (m *InitClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitClusterResponse.Unmarshal(m, b)
}
func (m *InitClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitClusterResponse.Marshal(b, m, deterministic)
}
func (m *InitClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitClusterResponse.Merge(m, src)
}
func (m *InitClusterResponse) XXX_Size() int {
	return xxx_messageInfo_InitClusterResponse.Size(m)
}
func (m *InitClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitClusterResponse proto.InternalMessageInfo

func (m *InitClusterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InitClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type PeerInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{4}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PeerInfo) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type JoinClusterRequest struct {
	Force                bool        `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Peers                []*PeerInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinClusterRequest) Reset()         { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()    {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{5}
}

func (m *JoinClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterRequest.Unmarshal(m, b)
}
func (m *JoinClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterRequest.Marshal(b, m, deterministic)
}
func (m *JoinClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterRequest.Merge(m, src)
}
func (m *JoinClusterRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClusterRequest.Size(m)
}
func (m *JoinClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterRequest proto.InternalMessageInfo

func (m *JoinClusterRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *JoinClusterRequest) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

type JoinClusterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterResponse) Reset()         { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()    {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_521003751d596b5e, []int{6}
}

func (m *JoinClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterResponse.Unmarshal(m, b)
}
func (m *JoinClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterResponse.Marshal(b, m, deterministic)
}
func (m *JoinClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterResponse.Merge(m, src)
}
func (m *JoinClusterResponse) XXX_Size() int {
	return xxx_messageInfo_JoinClusterResponse.Size(m)
}
func (m *JoinClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterResponse proto.InternalMessageInfo

func (m *JoinClusterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *JoinClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "driverpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "driverpb.StatusResponse")
	proto.RegisterType((*InitClusterRequest)(nil), "driverpb.InitClusterRequest")
	proto.RegisterType((*InitClusterResponse)(nil), "driverpb.InitClusterResponse")
	proto.RegisterType((*PeerInfo)(nil), "driverpb.PeerInfo")
	proto.RegisterType((*JoinClusterRequest)(nil), "driverpb.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "driverpb.JoinClusterResponse")
}

func init() { proto.RegisterFile("driver.proto", fileDescriptor_521003751d596b5e) }

var fileDescriptor_521003751d596b5e = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xdb, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x5a, 0x5b, 0xd3, 0x69, 0xeb, 0x65, 0x14, 0x0c, 0x45, 0xa1, 0xac, 0x20, 0x79, 0x2a,
	0x52, 0x7f, 0x40, 0x10, 0x94, 0x4a, 0x15, 0x59, 0xeb, 0xb3, 0xa4, 0x75, 0xaa, 0x81, 0x36, 0x1b,
	0x77, 0x36, 0x3e, 0xf8, 0xcd, 0x7e, 0x84, 0xa4, 0xbb, 0xe9, 0x85, 0x2a, 0xf8, 0xe0, 0xdb, 0x9e,
	0xb9, 0x9c, 0x99, 0x33, 0x67, 0xa1, 0xf9, 0xa2, 0xe3, 0x0f, 0xd2, 0xdd, 0x54, 0x2b, 0xa3, 0xd0,
	0xb7, 0x28, 0x1d, 0x89, 0x5d, 0x68, 0x3d, 0x9a, 0xc8, 0x64, 0x2c, 0xe9, 0x3d, 0x23, 0x36, 0xe2,
	0x0c, 0x76, 0x8a, 0x00, 0xa7, 0x2a, 0x61, 0xc2, 0x43, 0xa8, 0xb2, 0x89, 0x0c, 0x05, 0x5e, 0xc7,
	0x0b, 0xab, 0xd2, 0x02, 0x71, 0x0d, 0xd8, 0x4f, 0x62, 0x73, 0x35, 0xcd, 0xd8, 0x90, 0x76, 0xdd,
	0x79, 0xed, 0x44, 0xe9, 0xb1, 0xad, 0xf5, 0xa5, 0x05, 0xd8, 0x06, 0x9f, 0x93, 0x28, 0xe5, 0x37,
	0x65, 0x82, 0x72, 0xc7, 0x0b, 0xeb, 0x72, 0x81, 0xc5, 0x10, 0x0e, 0xd6, 0x78, 0xdc, 0xd0, 0x00,
	0xb6, 0x39, 0x1b, 0x8f, 0x89, 0xd9, 0x51, 0x15, 0x10, 0x4f, 0xa1, 0x45, 0x5a, 0x2b, 0xfd, 0x3c,
	0x23, 0xe6, 0xe8, 0x95, 0x1c, 0x63, 0x73, 0x1e, 0xbc, 0xb3, 0x31, 0x71, 0x0e, 0xfe, 0x03, 0x91,
	0xee, 0x27, 0x13, 0x85, 0x08, 0x5b, 0xf7, 0xd1, 0xcc, 0xae, 0x54, 0x97, 0xf3, 0x37, 0xee, 0x41,
	0xe5, 0x49, 0x0e, 0x5c, 0x6b, 0xfe, 0x14, 0x43, 0xc0, 0x5b, 0x15, 0x27, 0x7f, 0xd2, 0x13, 0x42,
	0x35, 0x25, 0xd2, 0x1c, 0x94, 0x3b, 0x95, 0xb0, 0xd1, 0xc3, 0x6e, 0x71, 0xce, 0x6e, 0x31, 0x54,
	0xda, 0x82, 0x5c, 0xdd, 0x1a, 0xeb, 0xbf, 0xa8, 0xeb, 0x7d, 0x79, 0x50, 0xb3, 0x23, 0xf1, 0x12,
	0xea, 0x37, 0x64, 0xac, 0x63, 0x78, 0xb4, 0x5c, 0x64, 0xcd, 0xd4, 0x76, 0xb0, 0x99, 0xb0, 0x9b,
	0x88, 0x12, 0x4a, 0xd8, 0xcf, 0x0d, 0x88, 0xa3, 0x69, 0xfc, 0x49, 0x6e, 0x51, 0x3c, 0x5e, 0x36,
	0x6c, 0xba, 0xdc, 0x3e, 0xf9, 0x25, 0xbb, 0xe0, 0x1c, 0x40, 0x63, 0x45, 0xf6, 0x2a, 0xdb, 0xe6,
	0x8d, 0x57, 0xd9, 0x7e, 0xb8, 0x95, 0x28, 0x8d, 0x6a, 0xf3, 0x4f, 0x7b, 0xf1, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x5c, 0x55, 0x47, 0xc4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriverClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	InitializeCluster(ctx context.Context, in *InitClusterRequest, opts ...grpc.CallOption) (*InitClusterResponse, error)
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/driverpb.driver/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InitializeCluster(ctx context.Context, in *InitClusterRequest, opts ...grpc.CallOption) (*InitClusterResponse, error) {
	out := new(InitClusterResponse)
	err := c.cc.Invoke(ctx, "/driverpb.driver/InitializeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, "/driverpb.driver/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
type DriverServer interface {
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	InitializeCluster(context.Context, *InitClusterRequest) (*InitClusterResponse, error)
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/driverpb.driver/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InitializeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InitializeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/driverpb.driver/InitializeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InitializeCluster(ctx, req.(*InitClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/driverpb.driver/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "driverpb.driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Driver_GetStatus_Handler,
		},
		{
			MethodName: "InitializeCluster",
			Handler:    _Driver_InitializeCluster_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _Driver_JoinCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
