// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conductor.proto

package conductorpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeInfoStatus int32

const (
	NodeInfoStatus_UNKNOWN NodeInfoStatus = 0
	NodeInfoStatus_RUNNING NodeInfoStatus = 1
	NodeInfoStatus_STOPPED NodeInfoStatus = 2
	NodeInfoStatus_FAILED  NodeInfoStatus = 3
)

var NodeInfoStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "STOPPED",
	3: "FAILED",
}

var NodeInfoStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"RUNNING": 1,
	"STOPPED": 2,
	"FAILED":  3,
}

func (x NodeInfoStatus) String() string {
	return proto.EnumName(NodeInfoStatus_name, int32(x))
}

func (NodeInfoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{0}
}

type NodeInfo struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string         `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status               NodeInfoStatus `protobuf:"varint,3,opt,name=status,proto3,enum=conductorpb.NodeInfoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NodeInfo) GetStatus() NodeInfoStatus {
	if m != nil {
		return m.Status
	}
	return NodeInfoStatus_UNKNOWN
}

type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{1}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	ErrorMessage         string      `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{2}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetStatusResponse) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetNodeStatusRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeStatusRequest) Reset()         { *m = GetNodeStatusRequest{} }
func (m *GetNodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusRequest) ProtoMessage()    {}
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{3}
}

func (m *GetNodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusRequest.Unmarshal(m, b)
}
func (m *GetNodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusRequest.Merge(m, src)
}
func (m *GetNodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusRequest.Size(m)
}
func (m *GetNodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusRequest proto.InternalMessageInfo

func (m *GetNodeStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNodeStatusResponse struct {
	ErrorMessage         string    `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Node                 *NodeInfo `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNodeStatusResponse) Reset()         { *m = GetNodeStatusResponse{} }
func (m *GetNodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusResponse) ProtoMessage()    {}
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_391fd6a51d8c9187, []int{4}
}

func (m *GetNodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusResponse.Unmarshal(m, b)
}
func (m *GetNodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusResponse.Merge(m, src)
}
func (m *GetNodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusResponse.Size(m)
}
func (m *GetNodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusResponse proto.InternalMessageInfo

func (m *GetNodeStatusResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetNodeStatusResponse) GetNode() *NodeInfo {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterEnum("conductorpb.NodeInfoStatus", NodeInfoStatus_name, NodeInfoStatus_value)
	proto.RegisterType((*NodeInfo)(nil), "conductorpb.NodeInfo")
	proto.RegisterType((*GetStatusRequest)(nil), "conductorpb.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "conductorpb.GetStatusResponse")
	proto.RegisterType((*GetNodeStatusRequest)(nil), "conductorpb.GetNodeStatusRequest")
	proto.RegisterType((*GetNodeStatusResponse)(nil), "conductorpb.GetNodeStatusResponse")
}

func init() { proto.RegisterFile("conductor.proto", fileDescriptor_391fd6a51d8c9187) }

var fileDescriptor_391fd6a51d8c9187 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4e, 0xfa, 0x40,
	0x14, 0xc5, 0x29, 0xe5, 0xcf, 0x5f, 0x2e, 0x82, 0xe3, 0x8d, 0x24, 0x0d, 0x46, 0x83, 0xe3, 0x06,
	0x31, 0x61, 0x01, 0x4f, 0x60, 0x04, 0x09, 0x11, 0x07, 0x52, 0x24, 0xba, 0x33, 0x7c, 0x5c, 0xd9,
	0x48, 0x07, 0x67, 0xa6, 0x4f, 0xe6, 0x0b, 0x9a, 0x0e, 0x1f, 0xa1, 0x15, 0x4c, 0xdc, 0xcd, 0xfc,
	0x7a, 0x7a, 0xcf, 0xb9, 0x27, 0x03, 0x27, 0x53, 0x19, 0xcc, 0xc2, 0xa9, 0x91, 0xaa, 0xbe, 0x54,
	0xd2, 0x48, 0xcc, 0x6f, 0xc1, 0x72, 0xc2, 0x09, 0x8e, 0x84, 0x9c, 0x51, 0x37, 0x78, 0x97, 0x88,
	0x90, 0x09, 0xc6, 0x0b, 0xf2, 0x9c, 0x8a, 0x53, 0xcd, 0xf9, 0xf6, 0x8c, 0x0c, 0xdc, 0x50, 0x7d,
	0x78, 0x69, 0x8b, 0xa2, 0x23, 0x36, 0x21, 0xab, 0xcd, 0xd8, 0x84, 0xda, 0x73, 0x2b, 0x4e, 0xb5,
	0xd8, 0x38, 0xaf, 0xef, 0xcc, 0xab, 0x6f, 0x86, 0x0d, 0xad, 0xc4, 0x5f, 0x4b, 0x39, 0x02, 0xeb,
	0x90, 0x59, 0x43, 0xfa, 0x0c, 0x49, 0x1b, 0x4e, 0x70, 0xba, 0xc3, 0xf4, 0x52, 0x06, 0x9a, 0xf0,
	0x1a, 0x0a, 0xa4, 0x94, 0x54, 0x6f, 0x0b, 0xd2, 0x7a, 0x3c, 0xdf, 0x84, 0x39, 0xb6, 0xf0, 0x69,
	0xc5, 0xf0, 0x16, 0xfe, 0x05, 0x72, 0x46, 0xda, 0x4b, 0x57, 0xdc, 0x6a, 0xbe, 0x51, 0xda, 0x9b,
	0xc0, 0x5f, 0x69, 0x78, 0x0d, 0xce, 0x3a, 0x64, 0x22, 0x1a, 0xb3, 0xdf, 0xb7, 0x2d, 0x9f, 0x43,
	0x29, 0xa1, 0xfd, 0x4b, 0xac, 0x1b, 0xc8, 0x44, 0x96, 0xb6, 0xac, 0x83, 0xa9, 0xac, 0xa4, 0x76,
	0x0f, 0xc5, 0x78, 0x53, 0x98, 0x87, 0xff, 0x23, 0xf1, 0x28, 0xfa, 0x2f, 0x82, 0xa5, 0xa2, 0x8b,
	0x3f, 0x12, 0xa2, 0x2b, 0x3a, 0xcc, 0x89, 0x2e, 0xc3, 0xe7, 0xfe, 0x60, 0xd0, 0x6e, 0xb1, 0x34,
	0x02, 0x64, 0x1f, 0xee, 0xba, 0xbd, 0x76, 0x8b, 0xb9, 0x8d, 0x2f, 0x07, 0x72, 0x5b, 0x0f, 0xec,
	0x41, 0x6e, 0x5b, 0x27, 0x5e, 0xc4, 0xcc, 0x93, 0xd5, 0x97, 0x2f, 0x0f, 0x7d, 0x5e, 0xad, 0xcb,
	0x53, 0xf8, 0x0a, 0x85, 0x58, 0x13, 0x78, 0x95, 0xfc, 0xe5, 0x47, 0xa3, 0x65, 0xfe, 0x9b, 0x64,
	0x33, 0x79, 0x92, 0xb5, 0xaf, 0xb0, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x03, 0xb4, 0x08, 0xd5,
	0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConductorClient is the client API for Conductor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConductorClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error)
}

type conductorClient struct {
	cc *grpc.ClientConn
}

func NewConductorClient(cc *grpc.ClientConn) ConductorClient {
	return &conductorClient{cc}
}

func (c *conductorClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/conductorpb.conductor/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conductorClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error) {
	out := new(GetNodeStatusResponse)
	err := c.cc.Invoke(ctx, "/conductorpb.conductor/GetNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConductorServer is the server API for Conductor service.
type ConductorServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetNodeStatus(context.Context, *GetNodeStatusRequest) (*GetNodeStatusResponse, error)
}

func RegisterConductorServer(s *grpc.Server, srv ConductorServer) {
	s.RegisterService(&_Conductor_serviceDesc, srv)
}

func _Conductor_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConductorServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductorpb.conductor/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConductorServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conductor_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConductorServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductorpb.conductor/GetNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConductorServer).GetNodeStatus(ctx, req.(*GetNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Conductor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conductorpb.conductor",
	HandlerType: (*ConductorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Conductor_GetStatus_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _Conductor_GetNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conductor.proto",
}
