// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conductor.proto

package conductorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeInfoStatus int32

const (
	NodeInfoStatus_UNKNOWN NodeInfoStatus = 0
	NodeInfoStatus_RUNNING NodeInfoStatus = 1
	NodeInfoStatus_STOPPED NodeInfoStatus = 2
	NodeInfoStatus_FAILED  NodeInfoStatus = 3
)

var NodeInfoStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "STOPPED",
	3: "FAILED",
}
var NodeInfoStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"RUNNING": 1,
	"STOPPED": 2,
	"FAILED":  3,
}

func (x NodeInfoStatus) String() string {
	return proto.EnumName(NodeInfoStatus_name, int32(x))
}
func (NodeInfoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{0}
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{0}
}
func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(dst, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	IsConductor          bool     `protobuf:"varint,1,opt,name=is_conductor,json=isConductor,proto3" json:"is_conductor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{1}
}
func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(dst, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetIsConductor() bool {
	if m != nil {
		return m.IsConductor
	}
	return false
}

type NodeInfo struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string         `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status               NodeInfoStatus `protobuf:"varint,3,opt,name=status,proto3,enum=conductorpb.NodeInfoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{2}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(dst, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NodeInfo) GetStatus() NodeInfoStatus {
	if m != nil {
		return m.Status
	}
	return NodeInfoStatus_UNKNOWN
}

type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{3}
}
func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(dst, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	ErrorMessage         string      `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{4}
}
func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(dst, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetStatusResponse) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetNodeStatusRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeStatusRequest) Reset()         { *m = GetNodeStatusRequest{} }
func (m *GetNodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusRequest) ProtoMessage()    {}
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{5}
}
func (m *GetNodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusRequest.Unmarshal(m, b)
}
func (m *GetNodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusRequest.Merge(dst, src)
}
func (m *GetNodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusRequest.Size(m)
}
func (m *GetNodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusRequest proto.InternalMessageInfo

func (m *GetNodeStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNodeStatusResponse struct {
	ErrorMessage         string    `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Node                 *NodeInfo `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNodeStatusResponse) Reset()         { *m = GetNodeStatusResponse{} }
func (m *GetNodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusResponse) ProtoMessage()    {}
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conductor_229289228fc57bce, []int{6}
}
func (m *GetNodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusResponse.Unmarshal(m, b)
}
func (m *GetNodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetNodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusResponse.Merge(dst, src)
}
func (m *GetNodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusResponse.Size(m)
}
func (m *GetNodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusResponse proto.InternalMessageInfo

func (m *GetNodeStatusResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetNodeStatusResponse) GetNode() *NodeInfo {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "conductorpb.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "conductorpb.GetInfoResponse")
	proto.RegisterType((*NodeInfo)(nil), "conductorpb.NodeInfo")
	proto.RegisterType((*GetStatusRequest)(nil), "conductorpb.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "conductorpb.GetStatusResponse")
	proto.RegisterType((*GetNodeStatusRequest)(nil), "conductorpb.GetNodeStatusRequest")
	proto.RegisterType((*GetNodeStatusResponse)(nil), "conductorpb.GetNodeStatusResponse")
	proto.RegisterEnum("conductorpb.NodeInfoStatus", NodeInfoStatus_name, NodeInfoStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConductorClient is the client API for Conductor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConductorClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error)
}

type conductorClient struct {
	cc *grpc.ClientConn
}

func NewConductorClient(cc *grpc.ClientConn) ConductorClient {
	return &conductorClient{cc}
}

func (c *conductorClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/conductorpb.conductor/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conductorClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/conductorpb.conductor/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conductorClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error) {
	out := new(GetNodeStatusResponse)
	err := c.cc.Invoke(ctx, "/conductorpb.conductor/GetNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConductorServer is the server API for Conductor service.
type ConductorServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetNodeStatus(context.Context, *GetNodeStatusRequest) (*GetNodeStatusResponse, error)
}

func RegisterConductorServer(s *grpc.Server, srv ConductorServer) {
	s.RegisterService(&_Conductor_serviceDesc, srv)
}

func _Conductor_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConductorServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductorpb.conductor/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConductorServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conductor_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConductorServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductorpb.conductor/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConductorServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conductor_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConductorServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductorpb.conductor/GetNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConductorServer).GetNodeStatus(ctx, req.(*GetNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Conductor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conductorpb.conductor",
	HandlerType: (*ConductorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Conductor_GetInfo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Conductor_GetStatus_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _Conductor_GetNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conductor.proto",
}

func init() { proto.RegisterFile("conductor.proto", fileDescriptor_conductor_229289228fc57bce) }

var fileDescriptor_conductor_229289228fc57bce = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5b, 0x4f, 0xf2, 0x40,
	0x10, 0x86, 0x29, 0xe5, 0xe3, 0x30, 0xe5, 0xd0, 0x6f, 0x22, 0x49, 0x83, 0x87, 0xc0, 0x7a, 0x83,
	0x98, 0x70, 0x01, 0xfe, 0x01, 0xc3, 0xa1, 0x21, 0x62, 0x21, 0x45, 0xa2, 0x77, 0x84, 0xc3, 0x4a,
	0x48, 0xa4, 0x8b, 0xdd, 0xed, 0xaf, 0xf7, 0xc6, 0x74, 0x69, 0x1b, 0x8a, 0x60, 0xe2, 0xdd, 0xee,
	0xb3, 0xef, 0xcc, 0xbc, 0x33, 0xd3, 0x42, 0x69, 0xc9, 0x9c, 0x95, 0xb7, 0x14, 0xcc, 0x6d, 0xee,
	0x5c, 0x26, 0x18, 0x6a, 0x11, 0xd8, 0x2d, 0x88, 0x0e, 0x45, 0x93, 0x8a, 0x81, 0xf3, 0xce, 0x6c,
	0xfa, 0xe9, 0x51, 0x2e, 0xc8, 0x03, 0x94, 0x22, 0xc2, 0x77, 0xcc, 0xe1, 0x14, 0x6b, 0x90, 0xdf,
	0xf0, 0x59, 0x14, 0x66, 0x28, 0x55, 0xa5, 0x9e, 0xb5, 0xb5, 0x0d, 0xef, 0x84, 0x88, 0x50, 0xc8,
	0x5a, 0x6c, 0x45, 0xfd, 0x30, 0x44, 0x48, 0x39, 0xf3, 0x2d, 0x95, 0xb2, 0x9c, 0x2d, 0xcf, 0xa8,
	0x83, 0xea, 0xb9, 0x1f, 0x46, 0x52, 0x22, 0xff, 0x88, 0x6d, 0x48, 0x73, 0x31, 0x17, 0x1e, 0x37,
	0xd4, 0xaa, 0x52, 0x2f, 0xb6, 0x2e, 0x9b, 0x07, 0xbe, 0x9a, 0x61, 0xb2, 0x89, 0x94, 0xd8, 0x81,
	0x94, 0x20, 0xe8, 0x26, 0x15, 0x01, 0x0c, 0x0c, 0x53, 0xf8, 0x7f, 0xc0, 0x02, 0xcb, 0xb7, 0x50,
	0xa0, 0xae, 0xcb, 0xdc, 0xd9, 0x96, 0x72, 0x3e, 0x5f, 0x87, 0x66, 0xf2, 0x12, 0x3e, 0xef, 0x19,
	0xde, 0xc3, 0x3f, 0x87, 0xad, 0x28, 0x37, 0x92, 0x55, 0xb5, 0xae, 0xb5, 0xca, 0x27, 0x1d, 0xd8,
	0x7b, 0x0d, 0x69, 0xc0, 0x85, 0x49, 0x85, 0x4f, 0x63, 0xe5, 0x4f, 0x75, 0x4b, 0xd6, 0x50, 0x3e,
	0xd2, 0xfe, 0xc5, 0xd6, 0x1d, 0xa4, 0xfc, 0x92, 0x72, 0x58, 0x67, 0x5d, 0x49, 0x49, 0xa3, 0x03,
	0xc5, 0xf8, 0xa4, 0x50, 0x83, 0xcc, 0xd4, 0x7a, 0xb2, 0x46, 0xaf, 0x96, 0x9e, 0xf0, 0x2f, 0xf6,
	0xd4, 0xb2, 0x06, 0x96, 0xa9, 0x2b, 0xfe, 0x65, 0xf2, 0x32, 0x1a, 0x8f, 0x7b, 0x5d, 0x3d, 0x89,
	0x00, 0xe9, 0xfe, 0xe3, 0x60, 0xd8, 0xeb, 0xea, 0x6a, 0xeb, 0x4b, 0x81, 0x5c, 0x54, 0x03, 0xfb,
	0x90, 0x09, 0xf6, 0x8f, 0xf1, 0x95, 0xc4, 0xbf, 0x93, 0xca, 0xd5, 0xe9, 0xc7, 0x7d, 0xa3, 0x24,
	0x81, 0x43, 0xc8, 0x45, 0x6b, 0xc1, 0xeb, 0x63, 0x71, 0x6c, 0x86, 0x95, 0x9b, 0x73, 0xcf, 0x51,
	0xb6, 0x37, 0x28, 0xc4, 0x26, 0x8a, 0xb5, 0xe3, 0x90, 0x1f, 0x9b, 0xa9, 0x90, 0xdf, 0x24, 0x61,
	0xe6, 0x45, 0x5a, 0xfe, 0x15, 0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x29, 0x61, 0xc2,
	0x28, 0x03, 0x00, 0x00,
}
